name: Valetudo Multi Mapper (dev)
version: 0.0.1
slug: valetudomultimapper
description: This is a simple companion service for Valetudo RE which generates the
  map pngs. It supports multiple valuetudo mqtt configrations within one instance.
url: https://github.com/holgerb/hassio-addons/tree/master/valetudo-mapper
webui: http://[HOST]:[PORT:3000]/api/map/image
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
ports:
  3000/tcp:
ports_description:
  3000/tcp: Port serving the floor plan (Not required for Ingress)
ingress: true
ingress_port: 3000
ingress_entry: api/map/image
panel_title: Valetudo RE Floorplan
panel_icon: mdi:floor-plan
map:
  - ssl
options:
  mapSettings:
    drawPath: true
    drawCharger: true
    drawRobot: true
    drawCurrentlyCleanedZones: false
    drawCurrentlyCleanedBlocks: false
    drawForbiddenZones: true
    drawVirtualWalls: true
    scale: 4
    gradientBackground: true
    autoCrop: 20
  mapColors: { }
  mqtt:
    robots:
      - identifier: rockrobo
        topicPrefix: valetudo
        mapDataTopic: valetudo/rockrobo/map_data
    autoconfPrefix: homeassistant
    broker_url: mqtt://user:pass@foobar.example
    caPath: ''
    minMillisecondsBetweenMapUpdates: 10000
    publishMapImage: true
    publishMapData: false
