name: Valetudo Multi Mapper (dev)
version: 0.0.1
slug: valetudomultimapper
description: This is a simple companion service for Valetudo RE which generates the
  map pngs. It supports multiple valuetudo mqtt configrations within one instance.
url: https://github.com/holgerb/hassio-addons/tree/master/valetudo-mapper
webui: http://[HOST]:[PORT:3000]/api/map/image
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
ports:
  3000/tcp:
ports_description:
  3000/tcp: Port serving the floor plan (Not required for Ingress)
ingress: true
ingress_port: 3000
ingress_entry: api/map/image
panel_title: Valetudo RE Floorplan
panel_icon: mdi:floor-plan
map:
  - ssl
